CREATE DATABASE MEDIA;

USE MEDIA;

CREATE TABLE NOTAS(
    IDNOTAS INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    NOTA FLOAT(10,2)
);

DROP TABLE NOTAS;

INSERT INTO NOTAS VALUES(NULL, "TESTE", 5);
